import 'dart:io';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:multi_select_flutter/multi_select_flutter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:permission_handler/permission_handler.dart';
import '/reusables/constants.dart'; // Adjust import path
import '../models/team_model.dart';
import '../models/player_model.dart';
import '../models/coach_model.dart';
import '../services/team_service.dart';
import '../services/player_service.dart';
import '../services/coach_service.dart';

class CreateTeamScreen extends StatefulWidget {
  const CreateTeamScreen({super.key});

  @override
  State<CreateTeamScreen> createState() => _CreateTeamScreenState();
}

class _CreateTeamScreenState extends State<CreateTeamScreen> {
  final _formKey = GlobalKey<FormState>();
  final _teamService = TeamService();
  final _nameController = TextEditingController();
  final _abbrController = TextEditingController();
  String? _selectedCoachId;
  List<String> _selectedPlayerIds = [];
  File? _imageFile;
  String? _logoUrl;

  final List<Player> _availablePlayers = [];
  final List<Coach> _availableCoaches = [];
  final List<String> _availableCoachesIds = []; // Tracks coach IDs with null teamId
  final ImagePicker _picker = ImagePicker();
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final PlayerService _playerService = PlayerService();
  final CoachService _coachService = CoachService();

  @override
  void initState() {
    super.initState();
    _fetchAvailablePlayers();
    _fetchAvailableCoaches();
  }

  Future<void> _fetchAvailablePlayers() async {
    final snapshot = await _playerService.fetchPlayers();
    setState(() {
      _availablePlayers.addAll(
        snapshot.where((player) => player.team == null),
      ); // Filter unassigned players
    });
  }

  Future<void> _fetchAvailableCoaches() async {
    final snapshot = await _coachService.fetchCoaches();
    setState(() {
      _availableCoaches.addAll(snapshot); // Include all coaches
      _availableCoachesIds.addAll(
        snapshot.where((coach) => coach.teamId == null).map((coach) => coach.id),
      ); // Track only unassigned coaches
    });
  }

  Future<bool> _requestPermission() async {
    if (Platform.isAndroid) {
      if (await Permission.storage.isGranted ||
          await Permission.photos.isGranted ||
          await Permission.mediaLibrary.isGranted) {
        return true;
      }

      if (await Permission.storage.request().isGranted) return true;

      // For Android 13+
      if (await Permission.photos.request().isGranted) return true;
      if (await Permission.mediaLibrary.request().isGranted) return true;

      return false;
    } else if (Platform.isIOS) {
      return await Permission.photos.request().isGranted;
    }
    return false;
  }

  Future<void> _pickImage() async {
    if (await _requestPermission()) {
      final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
      if (pickedFile != null) {
        final compressedFile = await _compressImage(File(pickedFile.path));
        if (mounted) {
          setState(() {
            _imageFile = compressedFile;
          });
        }
      }
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Permission denied for image access')),
      );
    }
  }

  Future<File> _compressImage(File file) async {
    final compressed = await FlutterImageCompress.compressAndGetFile(
      file.absolute.path,
      '${file.parent.path}/compressed_${DateTime.now().millisecondsSinceEpoch}.jpg',
      quality: 85,
      minHeight: 300,
      minWidth: 300,
    );
    if (compressed != null) {
      final sizeInBytes = await compressed.length();
      if (sizeInBytes > 150 * 1024) {
        throw Exception('Image size exceeds 150KB after compression');
      }
      return File(compressed.path);
    }
    return file;
  }

  Future<String> _uploadImage(File image) async {
    final ref = _storage.ref().child(
      'teams/${DateTime.now().millisecondsSinceEpoch}.jpg',
    );
    await ref.putFile(image);
    return await ref.getDownloadURL();
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate() && _imageFile != null) {
      try {
        _logoUrl = await _uploadImage(_imageFile!);
        final team = Team(
          id: '', // Will be auto-generated by TeamService
          name: _nameController.text,
          abbr: _abbrController.text,
          coachId: _selectedCoachId, // Nullable, only set if a coach is selected
          logoUrl: _logoUrl,
          players: _selectedPlayerIds,
        );
        await _teamService.addTeam(team);
        if (mounted) {
          context.go('/admin'); // Adjust route to return to dashboard
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error: $e')));
        }
      }
    } else if (_imageFile == null && mounted) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please select a logo')));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.push('/admin_panel'),
        ),
        title: const Text('Add New Team', style: AppTextStyles.headingStyle),
        backgroundColor: AppColors.primaryColor,
        foregroundColor: AppColors.whiteColor,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(labelText: 'Name'),
                  validator: (value) =>
                      value!.isEmpty ? 'Please enter a name' : null,
                ),
                const SizedBox(height: 20),
                TextFormField(
                  controller: _abbrController,
                  decoration: const InputDecoration(labelText: 'Abbreviation'),
                  validator: (value) =>
                      value!.isEmpty ? 'Please enter an abbreviation' : null,
                ),
                const SizedBox(height: 20),
                GestureDetector(
                  onTap: _pickImage,
                  child: AbsorbPointer(
                    child: TextFormField(
                      enabled: false,
                      decoration: InputDecoration(
                        labelText: 'Team Logo',
                        suffixIcon: const Icon(Icons.camera_alt),
                        errorText: _imageFile == null
                            ? 'Please select a logo'
                            : null,
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                DropdownButtonFormField<String>(
                  value: _selectedCoachId,
                  hint: const Text('Select Coach'),
                  items: _availableCoaches.map((coach) {
                    return DropdownMenuItem<String>(
                      value: coach.id,
                      enabled: _availableCoachesIds.contains(coach.id), // Only coaches with null teamId are clickable
                      child: Opacity(
                        opacity: _availableCoachesIds.contains(coach.id) ? 1.0 : 0.5, // Full opacity for clickable, low opacity for non-clickable
                        child: Text(coach.name),
                      ),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        _selectedCoachId = value;
                      });
                    }
                  },
                  validator: (value) => null, // CoachId is nullable, no validation required
                ),
                const SizedBox(height: 20),
                MultiSelectDialogField<String>(
                  items: _availablePlayers
                      .map(
                        (player) =>
                            MultiSelectItem<String>(player.id, player.name),
                      )
                      .toList(),
                  initialValue: _selectedPlayerIds,
                  title: const Text("Select Players"),
                  buttonText: const Text("Select Players"),
                  searchable: true, // optional: allows search
                  listType: MultiSelectListType.CHIP, // CHIP or LIST
                  onConfirm: (values) {
                    setState(() {
                      _selectedPlayerIds = values;
                    });
                  },
                  chipDisplay: MultiSelectChipDisplay(
                    onTap: (value) {
                      setState(() {
                        _selectedPlayerIds.remove(value);
                      });
                    },
                  ),
                ),
                const SizedBox(height: 20),
                ElevatedButton(
                  onPressed: _submitForm,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primaryColor,
                    foregroundColor: AppColors.whiteColor,
                  ),
                  child: const Text('Submit'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _abbrController.dispose();
    super.dispose();
  }
}